### PR TITLE
Update to latest version of RE2

### PR DESCRIPTION
**Pull request by ianp**
Hopefully self explanatory fro the title. Although it looks like a huge change 99% is the now RE2 code, the only project files that I've altered are `binding.gyp` and a couple of new entries in `.gitignore`.

A couple of notes: I've only built & tested this on OS X, I'll be able to get access to a Linux box to test there as well early next week. I haven't updated `package.json`, not sure how you want to increment the version number (assuming you accept this PR).

Cheers,
Ian.

### CODE REVIEW

**Comment by uhop** [comment]
First of all: thank you for doing it. It clearly required a lot of efforts.

Secondly: what the upgrade buys us? Better performance, new features, bugfixes, security improvements? Twice in the past I decided to upgrade, and didn't find a compelling reason. If you have any benchmarks, or references to RE2 commits, which fixed major issues, that would be nice to have to justify the update for our users.

`node-re2` is supposed to be a drop-in replacement for JavaScript regular expressions (given limitations), so it restricts us from introducing new features. OTOH, I am not opposed to introduce new features, if they have some tangible benefits for developers.

Another point rather technical: Github fails even to show the patch, and because it is not a git patch, I cannot use git tools to see it, and have to use Github, which fails, and the circle starts. :-) It would be nice, if the giant commit was split into smaller pieces, so I can review them piece-wise. Obviously I assume that guys did a great code with RE2, so I have to concentrate more on changes to the glue code I wrote for this project.

Alternatively I can clone your repository and review the difference between two trees using `meld` or something like that, but it will take more time, because I cannot do it on the go, and have to have some quality time.

**Comment by ianp** [comment]
The main thing is better Windows compatibility (e.g. see superscriptjs/superscript#274), but there are also some improvements in performance and memory consumption. It should still be a drop in replacement, the RE2 guys are pretty focussed on maintaining compatibility.

The only project file that has changed is the bindings, so you should be able to review it using `git diff HEAD..HEAD~1 binding.gyp` or similar (that works for me, you may not need the version range).

If you'd like me to break things up differently I'm happy to do so, but I'm not sure how it would make sense to split up the updated dependency.

**Comment by uhop** [comment]
Yes, it makes sense.

Yet, there are two points:

1. It would be better to use `RE2` as a sub-module, rather than include a copy of it.
2. It wasn't possible before, because `make` generated some source files using PERL and some Unix utilities (BTW, unavailable on Windows), so I had to generate them manually.
    * It means that every `RE2` installation can be different.
    * I have a principle of not modifying projects I do not control in any way, so the copy was used.

If they fixed (2) above, please consider using `RE2` as a sub-module. Let me know, if you need my help with it.

**Comment by ianp** [comment]
Totally agree that a submodule would be a better approach.

I'll take a look into how the Windows build works (I know that they have a `CMakeLists.txt` file in there, but am not 100% sure how it is used right now). I'll have to try to get access to a Windows machine with a dev env on it so it may take me a few days to get back to you on this.

**Comment by uhop** [comment]
Excellent. I myself have a Linux box as the main dev computer, and a Mac laptop. I can try/test on those, but unfortunately I have no Win dev box, so I hope you can cover that.

Looking forward to eliminate a copy in favor of a submodule!

**Comment by uhop** [comment]
This pull request is superceded by #7. It was merged and released as 1.4.

**Pull request closed without merging**
