### PR TITLE
Update to re2 2023-06-02

### PR DESCRIPTION
**Pull request by stefanor**
StringPiece is now an absl::string_view, with a slightly different API

### CODE REVIEW

**Comment by stefanor** [comment]
Ah, right. Tests are failing because we need abseil available for the build. The linux side I could easily contribute the CI bits. But Windows and macOS are less easy for me to contribute.

**Comment by uhop** [comment]
We are in the same boat. :-)

**Comment by stefanor** [comment]
Would you like to just vendor them like re2?

**Comment by uhop** [comment]
Yes, I think including them the same way (as a git submodule) makes sense.

**Comment by uhop** [comment]
One comment: we use C++20 to compile the project. IIRC, it has `std::string_view` defined. Do we really need more dependencies?

The question for `google/re2` guys would be: is it possible to use the standard library implementation, if available, and pull dependencies only when truly needed?

**Comment by stefanor** [comment]
I think their plan is to migrate to c++17, eventually, but use abseil's string_view until then: https://groups.google.com/g/re2-dev/c/m1Hqx2cMkY0

Abseil is used for other things, too.

**Comment by stefanor** [comment]
Finally, CI is passing. This is bundling a lot more abseil than I expected, but the MSVC complier seems to want them. Maybe its linker doesn't do `--as-needed`?

**Comment by uhop** [comment]
Published as 1.20.0.

**Pull request merged**
